### ISSUE TITLE
Landing Page Responsiveness

### ISSUE THREAD

**Issue by vizvarun** [winterofcode/2019#5]
![Untitled](https://user-images.githubusercontent.com/47146480/65483693-c7454600-deba-11e9-82fe-54b4451c09be.png)

 Also, the flat designs overlap the navbar

![1](https://user-images.githubusercontent.com/47146480/65483807-260abf80-debb-11e9-8c1c-d47f2e126339.png)

**Comment by bosecodes** [comment]
I guess this issue is resolved, I don't see a problem now.
